openapi: "3.0.0"
info:
  title: Sample API for `{{cookiecutter.project_name}}`
  version: "{{cookiecutter.version}}"
paths:
  /:
    get:
      description: Root path.
      responses:
        '200':
          description: Root response
          content:
            application/json:
              schema:
                required:
                  - hello
                properties:
                  hello:
                    type: string
                    pattern: world
  /hello:
    get:
      description: Generic hello.
      responses:
        '200':
          description: Generic hello response
          content:
            text/plain:
              schema:
                type: string
                pattern: hello
  /hello/{name}:
    get:
      description: Hello to a specific name.
      parameters:
        - name: name
          in: path
          description: The name to say hello to
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Hello to a specific name response
          content:
            application/json:
              schema:
                required:
                  - hello
                properties:
                  hello:
                    type: string
